### ISSUE TITLE
Compiling fails with ESPHome 2026.3.3 works with 2026.4.5

### ISSUE THREAD

**Issue by hiknmike007** [esphome-econet/esphome-econet#605]
Not a huge issue as it can be resolved by updating ESPHome Builder.  

TLDR: Previously working YAML fails compiling (but passes verification) using ESPHome 2026.3.3 with error below.  Worked under Econet version 3.2.0 + ESPHome 2026.3.3. Upgrading ESPhome to 2026.4.5 solved the compilation error.  My installation is customized and the solution to my issue could be in my customization.

**ESPHome Install Log:**
_src/esphome/components/econet/climate/econet_climate.cpp: 
In member function 'virtual void esphome::econet::EconetClimate::setup()':

src/esphome/components/econet/climate/econet_climate.cpp:104:11:
error: 'class esphome::econet::EconetClimate' has no member named 'set_supported_custom_presets'
104 |     this->set_supported_custom_presets(presets);
       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/esphome/components/econet/climate/econet_climate.cpp:112:11: 
error: 'class esphome::econet::EconetClimate' has no member named 'set_supported_custom_fan_modes'
112 |     this->set_supported_custom_fan_modes(fans);
       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compiling .pioenvs/waveshare-furnace/src/esphome/components/esp32/core.cpp.o
*** [.pioenvs/waveshare-furnace/src/esphome/components/econet/climate/econet_climate.cpp.o] Error 1_

**Longer story:**
Installation uses a Waveshare ESP32-S3-POE-ETH-8DI-8RO for econet HVAC Furnace, contact sensors, relays, and an i2c scale.  Was working successfully for several months.  I needed to invert a contact sensors and couldn't compile afterwards.

**Comment by tronikos** [comment]
In https://github.com/esphome-econet/esphome-econet/pull/597 I did set `min_version: "2026.4.0"`
Maybe you are not using econet_base.yaml?
